---
- name: Copy eth0
  copy:
    dest: /etc/network/interfaces.d/eth0
    src: eth0
    owner: root
    group: root
    mode: '0644'
  notify: restart networking
- name: Disable dhcpcd
  systemd:
    name: 'dhcpcd.service'
    enabled: no
    state: stopped
- name: Start NetworkManager
  systemd:
    name: 'networking.service'
    enabled: yes
    masked: no
    state: started
