api:
  dashboard: true
  insecure: true
  debug: true
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  traefik:
    address: ":8080"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
# tls:
#   stores:
#     default:
#       defaultCertificate: 
#         certFile: "/fullchain.pem"
#         keyFile: "/privkey.pem"
certificateResolvers:
  staging:
    acme:
      email: "dbrasholt@proton.me"
      storage: /acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: http
  production:
    acme:
      email: "dbrasholt@proton.me"
      storage: /acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: http
